### PR TITLE
Adding bitnob update to wallet_support.json

### PR DESCRIPTION
**Pull request by MichaelEjila**
Bitnob tested and added to wallet_support.json

### CODE REVIEW

**Comment by MichaelEjila** [comment]
Please review

**Comment by sbddesign** [comment]
@MichaelEjila Thanks for testing! Question: when you say it generates a BIP21s, is that the default for lightning? Or is that only when generating on-chain addresses?

Also, can you please move this up into the B's for alphabetical order?

**Comment by MichaelEjila** [comment]
> @MichaelEjila Thanks for testing! Question: when you say it generates a BIP21s, is that the default for lightning? Or is that only when generating on-chain addresses?
> 
> Also, can you please move this up into the B's for alphabetical order?

Thank you for responding!, The BIP21 is only generated with on-chain addresses.
I also moved "bitnob" to the right alphabetical position.

**Comment by sbddesign** [comment]
Thank you @MichaelEjila!

**Pull request merged**
