### PR TITLE
update wallet_support.json for Electrum

### PR DESCRIPTION
**Pull request by bitkarrot**

### CODE REVIEW

**Comment by sbddesign** [comment]
Thanks for testing @bitkarrot. I'm a little confused. In your file, you've said "yes" to "recognizes lightning". However, it seems like there is still [an open issue](https://github.com/spesmilo/electrum/issues/7253) for this feature.

**Comment by bitkarrot** [comment]
In the issue detail: electrum will scan a bip21 and scan lightning, but does not create bip21. The first 2 parts are merged into the main, the last item is a todo. 

see qt+android: add lightning URI support #7301, which has been merged.
https://github.com/spesmilo/electrum/pull/7301

> Thanks for testing @bitkarrot. I'm a little confused. In your file, you've said "yes" to "recognizes lightning". However, it seems like there is still [an open issue](https://github.com/spesmilo/electrum/issues/7253) for this feature.

**Comment by sbddesign** [comment]
> In the issue detail: electrum will scan a bip21 and scan lightning, but does not create bip21. The first 2 parts are merged into the main, the last item is a todo.

> see qt+android: add lightning URI support #7301, which has been merged.
> https://github.com/spesmilo/electrum/pull/7301

@bitkarrot I'm sorry, I'm still confused. The issue you linked (7301) is for the `lightning:` prefix which is completely separate from what we're trying to do here with the BIP21 URI.

As for the previous issue ([7253](https://github.com/spesmilo/electrum/issues/7253)), that remains open still.

So have you downloaded this app onto your Android phone and tested and verified that it works in spite of the issue still being open? Here is the test case most people are using.

qr-bip21-bolt11

If so, what is the exact name of this wallet? I'm assuming this is separate from the desktop version and is Android only?

**Comment by bitkarrot** [comment]
this issue will take a bit more time to resolve. 

<closing for now>

**Pull request closed without merging**
